# Generated by Django 3.1.4 on 2020-12-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('rss', models.URLField(primary_key=True, serialize=False)),
            ],
        ),
    ]
